version: 2
jobs:
  main:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: ./scripts/create-config.sh
      - run: python app_tests.py
      - run: pylint felfinder
workflows:
  version: 2
  build_and_test:
    jobs:
      - main
